config/routes.rb
DocAi::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'

  get  'inquiries/new' => 'inquiries#new', as: :new_inquiry
  post 'inquiries' => 'inquiries#create', as: :inquiries
  get  'inquiries/:id' => 'inquiries#show', as: :inquiry
  get  'inquiries' => 'inquiries#index'

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.save
    redirect_to @inquiry
  end

  def show
    @inquiry = Inquiry.find(params[:id])
  end

  def index
    @inquiries = Inquiry.all
  end

  private
    def inquiry_params
      params.require(:inquiry).permit(:age, :sex, :weight, :height)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inquiries/index.html.erb
<h1>All Inquiries</h1>
<% for x in @inquiries %>
  <p><%= x.inspect %></p>
<% end %>

app/views/inquiries/new.html.erb
<h1>問診票</h1>
<%= form_for :inquiry, url: inquiries_path do |f| %>
  <p><%= f.label :age %>: <%= f.text_field :age, :style => 'width: 30px' %></p>
  <p>
    <%= f.label :sex %><br>
    <%= f.radio_button :sex, :male, :checked => true  %> Male
    <%= f.radio_button :sex, :female %> Female
  </p>
  <p><%= f.label :height %>: <%= f.text_field :height, :style => 'width: 30px' %></p>
  <p><%= f.label :weight %>: <%= f.text_field :weight, :style => 'width: 30px' %></p>
  <p><%= f.submit '送信する' %></p>
<% end %>

app/views/inquiries/show.html.erb
<h1>問診票</h1>
<p><strong>Age: </strong><%= @inquiry.age %></p>
<p><strong>Sex: </strong><%= @inquiry.sex %></p>
<p><strong>Height: </strong><%= @inquiry.height %></p>
<p><strong>Weight: </strong><%= @inquiry.weight %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DocAi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to '問診を始める', new_inquiry_path %>


<h2>links for developers</h2>
<%= link_to 'All inquiries', inquiries_path %>